### ISSUE TITLE
feat: 메인화면 디테일 수정 및 디테일뷰 설정

### ISSUE THREAD

**Issue by Juhyeoklee** [RxKindergarten/SmokeWay#11]
### Task

- [x] 마커 이벤트 수정
- [x] 리스트뷰 정렬로직 추가
- [x] 눌렀을 때 디테일화면 설정
