### ISSUE TITLE
Firebase 연결

### ISSUE THREAD

**Issue by Juhyeoklee** [RxKindergarten/SmokeWay#12]
### Task

- [ ] 네트워크 매니저 생성
- [ ] 리얼타임 DB 생성
- [ ] 목 데이터 만들어 두ㄱ
